"""empty message

Revision ID: 3140726d5e3d
Revises: 
Create Date: 2023-01-13 14:24:51.198456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3140726d5e3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('key', mysql.VARCHAR(length=15), nullable=False))
    # ### end Alembic commands ###
