"""empty message

Revision ID: 6c091998548e
Revises: 
Create Date: 2023-01-14 01:26:53.365822

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c091998548e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'slug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('slug', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
