"""empty message

Revision ID: 6d332bbf9df7
Revises: 
Create Date: 2023-01-12 20:27:55.241797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d332bbf9df7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('key', sa.String(length=15), nullable=False))
    op.create_unique_constraint(None, 'user', ['key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'key')
    # ### end Alembic commands ###
